// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/public/_layout.tsx";
import * as $6 from "./routes/public/auth/google.tsx";
import * as $7 from "./routes/public/index.tsx";
import * as $8 from "./routes/public/log.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/public/_layout.tsx": $5,
    "./routes/public/auth/google.tsx": $6,
    "./routes/public/index.tsx": $7,
    "./routes/public/log.tsx": $8,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
